---

- name: Show Devices Config
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: NSO global variables
    include_vars:
      #The NSO YAML file will include the url for NSO with the jsonrpc resource
      #(e.g. http://localhost:8080/jsonrpc), the username and the password
      file: nso.yml
      name: nso

  - name: Device global variables
    include_vars:
      file: device.yml
      name: device

    - name: Show devices including operational data
      nso_show:
        url: "{{ nso.url }}"
        username: "{{ nso.username }}"
        password: "{{ nso.password }}"
        path: /ncs:devices/device{'{{ device.hostname }}'}/config/ios:interface/..
        operational: false
